### ISSUE TITLE
MAM policy can only be applied to Android or iOS client platforms.

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/memdocs.pl-pl#1]
When following the tutorial cannot save the policy getting the error:
`MAM policy can only be applied to Android or iOS client platforms.`

In order to save the policy you need to set the device platform to iOS and Android.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 733b08c2-5666-0d9b-8e78-28fba3456a6f
* Version Independent ID: ab6a321b-d6c0-c301-8156-96ccfdd21192
* Content: [Samouczek — chronienie poczty e-mail usługi Exchange Online na urządzeniach niezarządzanych - Microsoft Intune](https://docs.microsoft.com/pl-pl/mem/intune/protect/tutorial-protect-email-on-unmanaged-devices)
* Content Source: [memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md](https://github.com/MicrosoftDocs/memdocs.pl-pl/blob/live/memdocs/intune/protect/tutorial-protect-email-on-unmanaged-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by srvbpigh** [comment]
Hello, @Michal-Ziemba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Michal-Ziemba, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/memdocs/issues/294. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
